-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Base
import Test.Types
open Primitives
open test

/- [core::convert::num::{(core::convert::From<bool> for u8)#28}::from]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/convert/num.rs', lines 52:12-52:42
   Name pattern: core::convert::num::{core::convert::From<u8, bool>}::from -/
axiom core.convert.num.FromU8Bool.from : Bool → Result U8

/- [core::num::{u64#9}::leading_zeros]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/num/uint_macros.rs', lines 148:8-148:47
   Name pattern: core::num::{u64}::leading_zeros -/
axiom core.num.U64.leading_zeros : U64 → Result U32

/- [core::convert::num::{(core::convert::From<u32> for u64)#48}::from]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/convert/num.rs', lines 52:12-52:42
   Name pattern: core::convert::num::{core::convert::From<u64, u32>}::from -/
axiom core.convert.num.FromU64U32.from : U32 → Result U64

/- [core::convert::num::{(core::convert::From<u16> for u64)#46}::from]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/convert/num.rs', lines 52:12-52:42
   Name pattern: core::convert::num::{core::convert::From<u64, u16>}::from -/
axiom core.convert.num.FromU64U16.from : U16 → Result U64

/- [core::convert::num::{(core::convert::From<u8> for u64)#42}::from]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/convert/num.rs', lines 52:12-52:42
   Name pattern: core::convert::num::{core::convert::From<u64, u8>}::from -/
axiom core.convert.num.FromU64U8.from : U8 → Result U64

/- [core::num::{usize#11}::leading_zeros]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/num/uint_macros.rs', lines 148:8-148:47
   Name pattern: core::num::{usize}::leading_zeros -/
axiom core.num.Usize.leading_zeros : Usize → Result U32

/- [alloc::slice::{@Slice<T>}::to_vec]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/alloc/src/slice.rs', lines 412:4-414:17
   Name pattern: alloc::slice::{[@T]}::to_vec -/
axiom alloc.slice.Slice.to_vec
  (T : Type) (corecloneCloneInst : core.clone.Clone T) :
  Slice T → Result (alloc.vec.Vec T)

/- [core::clone::impls::{(core::clone::Clone for bool)#19}::clone]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/clone.rs', lines 181:20-181:43
   Name pattern: core::clone::impls::{core::clone::Clone<bool>}::clone -/
axiom core.clone.impls.CloneBool.clone : Bool → Result Bool

/- [alloc::vec::{(core::ops::deref::Deref for alloc::vec::Vec<T, A>)#9}::deref]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/alloc/src/vec/mod.rs', lines 2624:4-2624:27
   Name pattern: alloc::vec::{core::ops::deref::Deref<alloc::vec::Vec<@T, @A>>}::deref -/
axiom alloc.vec.DerefallocvecVec.deref
  (T A : Type) : alloc.vec.Vec T → Result (Slice T)

/- [alloc::vec::{(core::ops::deref::DerefMut for alloc::vec::Vec<T, A>)#10}::deref_mut]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/alloc/src/vec/mod.rs', lines 2632:4-2632:39
   Name pattern: alloc::vec::{core::ops::deref::DerefMut<alloc::vec::Vec<@T, @A>>}::deref_mut -/
axiom alloc.vec.DerefMutallocvecVec.deref_mut
  (T A : Type) :
  alloc.vec.Vec T → Result ((Slice T) × (Slice T → Result (alloc.vec.Vec
    T)))

/- [core::slice::{@Slice<T>}::reverse]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/slice/mod.rs', lines 941:4-941:29
   Name pattern: core::slice::{[@T]}::reverse -/
axiom core.slice.Slice.reverse (T : Type) : Slice T → Result (Slice T)

/- [alloc::vec::{alloc::vec::Vec<T, alloc::alloc::Global>}::with_capacity]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/alloc/src/vec/mod.rs', lines 478:4-478:49
   Name pattern: alloc::vec::{alloc::vec::Vec<@T, alloc::alloc::Global>}::with_capacity -/
axiom alloc.vec.VecTallocallocGlobal.with_capacity
  (T : Type) : Usize → Result (alloc.vec.Vec T)

/- [core::num::{u64#9}::to_le_bytes]:
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/num/uint_macros.rs', lines 2303:8-2303:70
   Name pattern: core::num::{u64}::to_le_bytes -/
axiom core.num.U64.to_le_bytes : U64 → Result (Array U8 8#usize)

