-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Base
import Test.Types
open Primitives
open test

/- [core::num::u128::{10}::pow]: forward function -/
axiom core.num.u128.pow : U128 → U32 → State → Result (State × U128)

