-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]: type definitions
import Base
open Primitives

namespace test

/- [test::arithmetics::BigInt]
   Source: 'src/arithmetics.rs', lines 2:0-2:33 -/
structure arithmetics.BigInt (N : Usize) where
  num : Array U64 N

/- Trait declaration: [core::default::Default]
   Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/default.rs', lines 102:0-102:24 -/
structure core.default.Default (Self : Type) where
  default : Result Self

/- Trait declaration: [test::arithmetics::BigInteger]
   Source: 'src/arithmetics.rs', lines 42:0-42:20 -/
structure arithmetics.BigInteger (Self : Type) where
  add_with_carry : Self → Self → Result (Bool × Self)

end test
