-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]: type definitions
import Base
open Primitives

namespace test

/- [test::arithmetics::BigInt] -/
structure arithmetics.BigInt where
  num : Array U64 (Usize.ofInt 4)

/- The state type used in the state-error monad -/
axiom State : Type

end test
